Feature to directly push notification without scheduling
Tweener/alarmee pull request #7
Opened 2024-12-30 15:48 UTC by Zubayer204

Sometimes, we need to push notifications immediately without scheduling. Much like what KMPNotifier does. But there's no direct function in Alarmee for that. We could basically schedule a notification after short time (say 1 second) as a workaround. But it is not robust because sometimes it takes a little bit of time to grant the permission and/or some time to actually process the notification request. This sometimes makes the scheduled time in a past date and causes it to automatically schedule it for next day which is not an expected behavior. So I have added a function in AlarmeeScheduler.kt file called `push` which follows the function signature of `schedule` function. Below are some example screenshots from iOS and Android where this `push` feature is implemented in the sample app.

## Android
<img src="https://github.com/user-attachments/assets/0409696b-3e61-422c-8d86-199f63902a6a" width="240">

## iOS
<img src="https://github.com/user-attachments/assets/c84d3a4e-6b74-4707-b898-b8c6d208ba13" width="240">

2025-01-02 08:59 UTC, Tweener requested changes
Hey @Zubayer204 , thank you for your contribution!

Great job with this PR! I just left a few comments for some minor changes to make before merging the PR.
Let me know what you think.

2025-01-02 08:59 UTC, Tweener commented on alarmee/src/commonMain/kotlin/com/tweener/alarmee/AlarmeeScheduler.kt
> +    abstract fun pushNotificationNow(alarmee: Alarmee, onSuccess: () -> Unit)
This method should be `internal` so it cannot be called outside of the library.
The name of the method could be slightly improved to keep a consistent naming with the other internal methods:
```suggestion
    internal abstract fun pushAlarmee(alarmee: Alarmee, onSuccess: () -> Unit)
```
(I don't think the `Now` is necessary since it's redundant with "push".)

2025-01-02 08:59 UTC, Tweener commented on alarmee/src/iosMain/kotlin/com/tweener/alarmee/AlarmeeSchedulerIos.kt
> +        val trigger = UNTimeIntervalNotificationTrigger.triggerWithTimeInterval(1.0, false)
I think that's the behavior to avoid, according to the description of your PR:
```We could basically schedule a notification after short time (say 1 second) as a workaround. But it is not robust because sometimes it takes a little bit of time to grant the permission and/or some time to actually process the notification request.```.

According to the [iOS official documentation](https://developer.apple.com/documentation/usernotifications/unnotificationrequest/init(identifier:content:trigger:)), we just have to set `trigger = null` to send the notification right away:
```The condition that causes the system to deliver the notification. Specify nil to deliver the notification right away.```

We just need to update `configureNotification()` signature with `notificationTrigger: UNNotificationTrigger? = null` and call `configureNotification(..., notificationTrigger = null, ...)`.


Can you test that behavior and see if it indeed works this way? Thanks!

2025-01-02 08:59 UTC, Tweener commented on alarmee/src/androidMain/kotlin/com/tweener/alarmee/AlarmeeSchedulerAndroid.kt
> +                notificationManager.notify(alarmee.uuid.hashCode(), notification)
`notification` here can be null if `channelId` was null previously. And according to the documentation of the `notificationManager.notify()` method, it should not be null:
```notification – A Notification object describing what to show the user. Must not be null.```.

Can you update this part of the code to avoid that? Thanks!

2025-01-02 08:59 UTC, Tweener commented on alarmee/src/androidMain/kotlin/com/tweener/alarmee/AlarmeeSchedulerAndroid.kt
> +        }
Note for myself: This will need to be refactored to avoid code duplication with `NotificationBroadcastReceiver` but for the scope of this PR, this is okay.

2025-01-03 01:19 UTC, Zubayer204 commented on alarmee/src/commonMain/kotlin/com/tweener/alarmee/AlarmeeScheduler.kt
> +    abstract fun pushNotificationNow(alarmee: Alarmee, onSuccess: () -> Unit)
That's a necessary change! Thanks for pointing it out!

2025-01-03 01:46 UTC, Zubayer204 commented on alarmee/src/iosMain/kotlin/com/tweener/alarmee/AlarmeeSchedulerIos.kt
> +        val trigger = UNTimeIntervalNotificationTrigger.triggerWithTimeInterval(1.0, false)
I overlooked that. Thank you for pointing out! I have tested it and it does indeed work. This is fixed in #236537b commit

2025-01-04 09:28 UTC, Tweener approved these changes

2025-01-04 09:28 UTC, merged